spring:
  datasource:
    url: jdbc:sqlite:test.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: com.sqlitee.config.SQLiteDialect
    show-sql: true